#' Identifies outliers on a graph for a certain parameter.
#'
#' @param upstream_slopes_test A data frame generated by the @extract_slope_params function.
#' @param parameter_of_interest The slope parameter you wish to investigate.
#' @param species The species to analyse
#'
#' @return A subset of @upstream_slopes_test which contains only outliers.
#'
#' @examples
#' identify_outliers(slope_max, upstream_slopes_test)
#' # Will have to zoom on graph and click outliers
#' @export

# parameter_of_interest <- "slope_max"


identify_outliers <- function(upstream_slopes_test,parameter_of_interest,species) {
  par(mfrow = c(1,1))
  plot(upstream_slopes_test[,species] ~ upstream_slopes_test[,parameter_of_interest], xlab = parameter_of_interest, ylab = paste(species,"upstream"), main = paste(species,"presence/absence by",parameter_of_interest))

  outliers <- identify(x = upstream_slopes_test[,parameter_of_interest],
                       y = upstream_slopes_test[,species])
  outliers <- connectivity[outliers,]
  print(paste(nrow(outliers)," outliers identified", sep=""))
  return(outliers)
}

# identify_outliers_test <- identify_outliers(upstream_slopes_test,"slope_max")

