#' Identifies outliers on a graph for a certain parameter.
#'
#' @param upstream_slopes_test A data frame generated by the @extract_slope_params function.
#' @param parameter_of_interest The slope parameter you wish to investigate.
#'
#' @return A subset of @upstream_slopes_test which contains only outliers.
#'
#' @examples
#' identify_outliers(slope_max, upstream_slopes_test)
#' # Will have to zoom on graph and click outliers

# parameter_of_interest <- "slope_max"

identify_outliers <- function(upstream_slopes_test,parameter_of_interest) {
  par(mfrow = c(1,1))
  plot(data=upstream_slopes_test,Present ~ upstream_slopes_test[,parameter_of_interest], xlab = parameter_of_interest, ylab = "Presence/absence upstream", main = paste("Perch presence/absence by",parameter_of_interest))

  outliers <- identify(x = upstream_slopes_test[,parameter_of_interest],
                       y = upstream_slopes_test$Present)
  outliers <- connectivity[outliers,]
  print(paste(nrow(outliers)," outliers identified", sep=""))
  return(outliers)
}

# identify_outliers_test <- identify_outliers(upstream_slopes_test,"slope_max")

